#开发环境配置
server:
  #端口
  port: 8081
  tomcat:
    uri-encoding: utf-8
#日志配置
logging:
  level:
    com.xl.oa.project.mapper: debug
#数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_springboot_oa?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


# MyBatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.xl.oa.project.po
  configuration:
    map-underscore-to-camel-case: true

ylrc:
  upload:
    file:
      path: T:/idea-project1/SpringBootOA/src/main/resources/static/upload/

